MangaOnline/Client.Manager/Controllers/ManagerController.cs
using Microsoft.AspNetCore.Mvc;
using Service.MangaOnline.ResponseModels;
using System.Net.Http.Headers;
using System.Text.Json;
using Service.MangaOnline.Commons;
using Service.MangaOnline.Models;

namespace Client.Manager.Controllers;

public class ManagerController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly HttpClient client = null;
    private string ServiceMangaUrl = "";

    public ManagerController(ILogger<HomeController> logger)
    {
        client = new HttpClient();
        var contentType = new MediaTypeWithQualityHeaderValue("application/json");
        client.DefaultRequestHeaders.Accept.Add(contentType);
        ServiceMangaUrl = "http://localhost:5098/";
        _logger = logger;
    }
    // GET
    public IActionResult AddManga()
    {
        return View();
    }

    public IActionResult UpdateManga(Guid id)
    {
        return View("AddManga");
    }
    public async Task<IActionResult> Follow(Guid userId)
    {
        HttpResponseMessage response = await client.GetAsync(ServiceMangaUrl + "manga/FollowManga?userId="+ userId);
            string responseBody = await response.Content.ReadAsStringAsync();
            var option = new JsonSerializerOptions()
            { PropertyNameCaseInsensitive = true };
            var list = JsonSerializer.Deserialize<FollowResponse>(responseBody, option);
            ViewBag.list = list;
        return View("FollowManga");
    }

    public async Task<IActionResult> UnFollow(Guid userId,Guid mangaId)
    {
        HttpResponseMessage response = await client.DeleteAsync(ServiceMangaUrl + "manga/FollowManga?userId="+ userId+ "&&mangaId="+mangaId);
        return Redirect("follow?userId="+userId);
    }

    public async Task<IActionResult> ViewAddChapter(Guid id)
    {
        var response = await client.GetAsync(ServiceMangaUrl + "manga/GetManga?id="+ id);
        string responseBody = await response.Content.ReadAsStringAsync();
        var option = new JsonSerializerOptions
            { PropertyNameCaseInsensitive = true };
        var data = JsonSerializer.Deserialize<DataMangaResponse>(responseBody, option);
        ViewData["manga"] = data!.data;
        return View("AddChapter");
    }

    public async Task<IActionResult> AddChapter()
    {
        IFormFile file = Request.Form.Files.GetFile("fileUp")!;

        Chaptere chaptere = new Chaptere();
        chaptere.ChapterNumber = int.Parse(Request.Form["ChapNumber"]);
        chaptere.Id = Guid.NewGuid();
        chaptere.SubId = 0;
        chaptere.MangaId = Guid.Parse(Request.Form["mangaId"]);
        chaptere.Name = " Chapter "+ Request.Form["ChapNumber"];
        chaptere.CreatedAt = DateTimeOffset.Now;
        chaptere.Status = Int32.Parse(Request.Form["Status"]);
        chaptere.IsActive = true;
        //chaptere.FilePDF = _logicHandler.CreatePDF(file);
        
        string apiEndpoint = "http://localhost:5098/File/CreateImage";
        var formData = new MultipartFormDataContent();
        formData.Add(new StreamContent(file.OpenReadStream()), "imageFile", file.FileName);
        var response = await client.PostAsync(apiEndpoint, formData);
        if (response.IsSuccessStatusCode)
        {
            string responseBody = await response.Content.ReadAsStringAsync();
            var option = new JsonSerializerOptions
                { PropertyNameCaseInsensitive = true };
            var data = JsonSerializer.Deserialize<DataResponse>(responseBody, option);
            chaptere.FilePdf = data!.data;
            
            string apiC = "http://localhost:5098/Manga/AddChapter";
            var formContent = new FormUrlEncodedContent(new[] {
                new KeyValuePair<string,string>("ChapterNumber", chaptere.ChapterNumber.ToString()),
                new KeyValuePair<string,string>("SubId", chaptere.SubId.ToString()),
                new KeyValuePair<string,string>("MangaId", chaptere.MangaId.ToString()),
                new KeyValuePair<string,string>("Name", chaptere.Name),
                new KeyValuePair<string,string>("Status", chaptere.Status.ToString()),
                new KeyValuePair<string,string>("IsActive", chaptere.IsActive.ToString()),
                new KeyValuePair<string,string>("FilePDF", chaptere.FilePdf)
            });
            var responseC = await client.PostAsync(apiC, formContent);
            if (responseC.IsSuccessStatusCode)
            {
                return Redirect("/Public/DetailManga?id="+Request.Form["mangaId"]); 
            }
        }
        return View("Error");
    }

    public async Task<IActionResult> ListManga(string? genre, 
        string? status, string? statusOff, string? sort,int index)
    {
        genre = string.IsNullOrEmpty(genre) ? "Tất cả":genre;
        status = string.IsNullOrEmpty(status) ? "Tất cả" : status;
        statusOff = string.IsNullOrEmpty(statusOff) ? "Tất cả" : statusOff;
        sort = string.IsNullOrEmpty(sort) ? "Tất cả" : sort;
        HttpResponseMessage response = 
            await client.GetAsync(
                ServiceMangaUrl 
                + $"Manga/listManga?genre={genre}&status={status}&statusOff={statusOff}&sort={sort}&index={index}");
        string responseBody = await response.Content.ReadAsStringAsync();
        var option = new JsonSerializerOptions()
            { PropertyNameCaseInsensitive = true };
        var responseData = JsonSerializer.Deserialize<DataListMangaResponse>(responseBody, option);
        ViewData["ListManga"] = responseData!.data;
        ViewData["genre"] = genre;
        ViewData["status"] = status;
        ViewData["statusOff"] = statusOff;
        ViewData["sort"] = sort;
        ViewData["index"] = index==0?1:index;
        ViewData["LastPage"] = responseData.lastPage;
        return View("ListMangaManager");
    }
}

MangaOnline/Client.Manager/Views/Shared/Components/FormatNumberViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Client.Manager.Views.Shared.Components;

public class FormatNumberViewComponent : ViewComponent
{
    public string Invoke(int countView)
    {
        if (countView >= 1000000000)
        {
            return (countView / 1000000000) + "B";
        }
        else if (countView >= 1000000)
        {
            return (countView / 1000000) + "M";
        }
        else if (countView >= 1000)
        {
            return (countView / 1000) + "K";
        }
        else
        {
            return countView.ToString();
        }
    }
}

MangaOnline/Client.Manager/Views/Manager/AddChapter.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Service.MangaOnline.Commons
@using Service.MangaOnline.ResponseModels

@{
    Layout = "_Layout";
    var manga = (MangaResponse)ViewData["manga"]!;
    ViewData["title"] = "Add Chapter";
}

<link rel="stylesheet" href="~/css/AddManga.css">
<div class="sign section--bg">
    <div class="container-add">
            
        <div class="row">
            <div class="col-12">
         
                <div class="sign__content" style="padding-top: 100px;">
                    <!-- add form -->
                    <form method="post" action="AddChapter" class="sign__form form-addManga"  enctype="multipart/form-data">
                        <div class="title-addManga">
                            <h1>Thêm Chapter</h1>
                        </div>
                        <div class="col-12" style="display: flex;">
                            <div class="col-sm-4">
                                <div class="input-group-add">
                                    <p class="input-title">Tên Manga</p>
                                    <input type="text" readonly value="@manga.Name" class="sign__input">
                                    <input type="text" name="mangaId" hidden value="@manga.Id" >
                                </div>
                                <div class="input-group-add">
                                    <p class="input-title">Chapter Number</p>
                                    <input type="number" name="ChapNumber" class="sign__input">
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="input-group-add">
                                    <p class="input-title" required
                                    >UpLoad</p>
                                    <input type="file"  id="fileInput"
                                           class="input-file-image"
                                           accept=".pdf"  name="fileUp" onchange="setfilename(this.value)"/>
                                    <input type="text" name="wpName" id="wpName" class="sign__input">
                                </div>
                                
                                <div class="input-group-add">
                                    <p class="input-title">Trạng thái</p>
                                    <div class="radio-group ">
                                        <label class="container active-input" >
                                            Miễn phí <input name="Status" value="@((int)ChapterEnum.Normal)" type="radio" checked>
                                            <span class="checkmark"></span>
                                        </label>
                                        <label class="container active-input">
                                            Trả phí <input name="Status" value="@((int)ChapterEnum.Vip)" type="radio">
                                            <span class="checkmark"></span>
                                        </label>
                                    </div>
                                </div>
                                
                            </div>
                            
                           
                            
                            <div class="col-sm-4">
                                <div>
                                    <div style="max-height: 120px;margin-bottom:10px">
                                        <button class="sign__btn" id="submitBtn" type="submit">Thêm chapter</button>
                                    </div>
                                         @*  <div style="display:none;color: green;font-size:12px;" id="done_success">Add thành công chapter mới</div> *@
                                         @* <div style="display:none" id="take_notice">@ViewData["done"]</div> *@
                                </div>
                            </div>
                             
                            </div>
</form>
                    <!-- add form -->
                </div>
            </div>
        </div>
    </div>
</div>
   <script>
     window.onload = async()=>{
       if(document.getElementById("take_notice").innerHTML === "1"){
          onNotice();
       }
    }
    function onNotice(){
       document.getElementById("done_success").style.display="block";
       sleep(1000);
       
    }
    function sleep(ms){
    return new Promise(resolve => setTimeout(()=>{
        document.getElementById("done_success").style.display="none";
    }, ms));
    }
     function setfilename(val)
            {
                filename = val.split('\\').pop().split('/').pop();
                document.getElementById('wpName').value = filename;
            }

   </script>

MangaOnline/Client.Manager/Views/Manager/FollowManga.cshtml
@using Newtonsoft.Json
@using Service.MangaOnline.ResponseModels
@{
    ViewData["Title"] = "List Follow";
    FollowResponse followResponse = ViewBag.list;
    Layout = "_Layout";
}

<link rel="stylesheet" href="~/css/DetailManga.css">

<!-- page title -->
<section class="section section--first section--bg" data-bg="img/section/section.jpg">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section__wrap">
                    <!-- section title -->
                    <h2 class="section__title">Truyện đang theo dõi</h2>
                    <!-- end section title -->

                    <!-- breadcrumb -->
                    <ul class="breadcrumb">
                        <li class="breadcrumb__item">
                            <a asp-page="/Index">Trang chủ</a>
                        </li>
                        <li class="breadcrumb__item breadcrumb__item--active">Theo Dõi</li>
                    </ul>
                    <!-- end breadcrumb -->
                </div>
            </div>
        </div>
    </div>
</section>
<!-- end page title -->
    @if(followResponse.list.Count == 0)
    {
        <div style="display: flex; justify-content: center; align-items: center">
            <p class="breadcrumb__item breadcrumb__item--active" style="margin-left: 16px; margin-top: 16px">
                Bạn chưa theo dõi truyện nào cả. Để theo dõi truyện, nhấn vào <u>Theo dõi</u> như hình bên:
            </p>
            <p>
                <img src="/image/huong-dan-theo-doi-truyen.jpg" alt="Hướng dẫn theo dõi truyện tranh" 
                     width="660" style="margin-left: 16px; margin-top: 16px"/>
            </p>
        </div>
    }
    else
    {
        <!-- catalog -->
        <div class="catalog" style="padding-top: 20px">
            <div class="container">
                <div class="row">
                    <!-- card -->
                    @foreach (var manga in followResponse.list)
                    {
                        <div class="col-6 col-sm-4 col-lg-3 col-xl-2">
                            <div class="card">
                                <div class="card__cover">
                                    <img src="/image/manga-image/@manga.Image" alt="@manga.Name" style="height: 237.03px; width: 160px;">
                                    <a href="/Public/DetailManga?id=@manga.Id" class="card__play">
                                        <i class="icon ion-ios-play"></i>
                                    </a>
                                </div>
                                <div class="card__content">
                                    <h3 class="card__title">
                                        <a href="/Public/DetailManga?id=@manga.Id">@manga.Name</a>
                                    </h3>
                                    <span class="card__category">
                                        @{
                                            foreach (var category in manga.CategoryMangas)
                                            {
                                                <a asp-page="/Public/CategoriesList" asp-route-cateName="@category.Name">@category.Name</a>
                                            }
                                        }
                                    </span>
                                    <span class="card__rate"><i class="icon ion-ios-star"></i>@manga.Star</span>                                  
                                         <form method="post" action="/manager/unfollow">
                                        <input name="mangaId" value="@manga.Id" hidden/>
                                         <input id="userId" name="userId" hidden/>
                                        <button type="submit" class="button-unfollow">
                                            <i class="fa fa-times"></i>
                                            <span>Bỏ theo dõi</span>
                                        </button>
                                    </form>

                                </div>
                            </div>
                        </div>
                    }
                    <!-- end card -->
                </div>
            </div>
        </div>
        <!-- end catalog -->
    }
}
<script>
 $(document).ready(function() {
     let user = GetUserData()
    $("#userId").val(user.userId);
    resetNotiFollow();
});

function GetUserData() {
    const user = localStorage.getItem("USER_DATA");
    return $.parseJSON(user);
    // {"userId":"ef20386b-2335-4f65-87b2-819e1aef6612","userName":"traicv","email":"enm55606@nezid.com","role":"UserNormal","avartar":null}
}
</script>

 

MangaOnline/Client.Manager/Views/Manager/ListMangaManager.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Service.MangaOnline.Commons
@using Service.MangaOnline.ResponseModels


@{
    Layout = "_Layout";
    var listManga = (List<MangaResponse>?)ViewData["ListManga"];
    var genre = ViewData["genre"];
    var status = ViewData["status"];
    var statusOff = ViewData["statusOff"];
    var sort = ViewData["sort"];
    var index = (int)ViewData["index"]!;
    var lastPage = (int)ViewData["LastPage"]!;
}
<link rel="stylesheet" href="~/css/Notification.css">
<link rel="stylesheet" href="~/css/MangaListManager.css">
@{
    var routeUrl = Url.RouteUrl(ViewContext.RouteData.Values);
    routeUrl = routeUrl + "?genre=" + genre + "&status=" + status + "&statusOff=" + statusOff + "&sort=" + sort + "&index=";
}
<div class="container border-list">
<div class="row">
<div class="col-lg-12">
<form method="get">
    @* filter *@
    <div class="border-filter">
        <!-- filter item -->
        <div class="filter__item" id="filter__genre">
            <span class="filter__item-label">Thể loại:</span>

            <div class="filter__item-btn dropdown-toggle" role="navigation" id="filter-genre"
                 data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <input type="button" value="@genre">
                <input asp-for="@genre" type="text" hidden/>
                <span></span>
            </div>

            <ul class="filter__item-menu dropdown-menu scrollbar-dropdown" aria-labelledby="filter-genre">
                <li>Tất cả</li>
                @foreach (var cate in AllCategory.GetAll)
                {
                    <li>@cate.Name</li>
                }
            </ul>
        </div>

        <div class="filter__item" id="filter__status">
            <span class="filter__item-label">Trạng thái:</span>

            <div class="filter__item-btn dropdown-toggle" role="navigation" id="filter-status" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <input type="button" value="@status">
                <input asp-for="@status" type="hidden">
                <span></span>
            </div>

            <ul class="filter__item-menu dropdown-menu scrollbar-dropdown" aria-labelledby="filter-status">
                <li>Tất cả</li>
                <li>Hoàn thành</li>
                <li>Đang cập nhật</li>
                <li>Dừng cập nhật</li>
            </ul>
        </div>
        <div class="filter__item" id="off__status">
            <span class="filter__item-label">Ẩn/Hiện:</span>
            <div class="filter__item-btn dropdown-toggle" role="navigation" id="off-status" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <input type="button" value="@statusOff">
                <input asp-for="@statusOff" type="hidden">
                <span></span>
            </div>
            <ul class="filter__item-menu dropdown-menu scrollbar-dropdown" aria-labelledby="off-status">
                <li>Tất cả</li>
                <li>Đang ẩn</li>
                <li>Đang hiện</li>
            </ul>
        </div>
        <div class="filter__item" id="filter__sort">
            <span class="filter__item-label">Sắp xếp:</span>
            <div class="filter__item-btn dropdown-toggle" role="navigation" id="Sort" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <input type="button" value="@sort">
                <input asp-for="@sort" type="hidden">
                <span></span>
            </div>
            <ul class="filter__item-menu dropdown-menu scrollbar-dropdown" aria-labelledby="Sort">
                <li>Tất cả</li>
                <li>Lượt xem cao</li>
                <li>Lượt đánh giá cao</li>
                <li>Lượt theo dõi cao</li>
            </ul>
        </div>
        <div class="label-apply">
            <div class="filter__item" style="margin-right: 20px;">
                <a href="/Manager/ListManga">
                    <div class="btn-status-plink">
                        <i class="icon ion-ios-refresh-circle"></i>
                    </div>
                </a>
            </div>
            <div class="filter__item">
                <button class="btn-status-plink" type="submit">
                    Áp dụng
                </button>
            </div>
        </div>
        <!-- end filter item -->
    </div>
    @* filter *@
</form>
<div class="main-box clearfix">
    <div class="table-responsive">
        <table border="1px" class="table table-hover table-dark user-list">
            <thead>
            <tr>
                <th scope="col">Ảnh bìa</th>
                <th scope="col">Tên manga</th>
                <th scope="col">Tác giả</th>
                <th scope="col">Thể loại</th>
                <th scope="col">Thông số</th>
                <th scope="col">Năm</th>
                <th scope="col">Trạng thái</th>
                <th scope="col">Hành động</th>
            </tr>
            </thead>
            <tbody>
            @if (listManga != null)
            {
                @foreach (var manga in listManga)
                {
                    <tr>
                        <th style="text-align: center;padding: 10px 0px;">
                            <img class="avatar1" src="/image/manga-image/@manga.Image" alt="">
                        </th>
                        <th class="name-manga">@manga.Name</th>
                        <th>@manga.AuthorName</th>
                        <th>
                            <span class="card__category">
                                @foreach (var categoryManga in manga.CategoryMangas)
                                {
                                    <a asp-page="/Public/CategoriesList" asp-route-cateName="@categoryManga.Name">@categoryManga.Name</a>
                                }
                            </span>
                        </th>
                        <th>
                            <p>
                                <span class="card__rate" style="color: #a1a1a1">
                                    <i class="icon ion-ios-star"></i>@manga.Star
                                </span>
                            </p>
                            <p>
                                <span class="card__rate" style="color: #a1a1a1">
                                    <i class="icon ion-ios-eye"></i>@await Component.InvokeAsync("FormatNumber", manga.ViewCount)
                                </span>
                            </p>
                            <p>
                                <span class="card__rate" style="color: #a1a1a1">
                                    <i class="icon ion-ios-people"></i>@await Component.InvokeAsync("FormatNumber", manga.FollowCount)
                                </span>
                            </p>
                        </th>
                        <th>@manga.CreatedAt!.Value.Year</th>
                        <th>
                            @{
                                var statusString = manga.Status switch
                                {
                                    (int)MangaStatus.Done => "Hoàn thành",
                                    (int)MangaStatus.Updating => "Đang cập nhật",
                                    (int)MangaStatus.StopUpdating => "Dừng cập nhật",
                                    _ => ""
                                    };
                            }
                            @statusString
                        </th>
                        <th >
                            <div style="display: flex;    justify-content: center;">
                                <span id="isActive-@manga.Id">
                                    @if (manga.IsActive)
                                    {
                                        <button class="btn-status-green" type="submit" onclick="ChangeIsActive('@manga.Id','@manga.IsActive')">
                                            <i class="icon ion-ios-eye"></i>
                                        </button>
                                    }
                                    else
                                    {
                                        <button class="btn-status-red" type="submit" onclick="ChangeIsActive('@manga.Id','@manga.IsActive')">
                                            <i class="icon ion-ios-eye-off"></i>
                                        </button>
                                    }
                                </span>
                                <form method="get"></form>
                                <a href="/Manager/AddManga?id=@manga.Id">
                                    <button class="btn-status-blue" type="submit" style="margin-left: 5px;">
                                        <i class="icon ion-ios-create"></i>
                                    </button>
                                </a>
                            </div>
                        </th>
                    </tr>
                }
            }
            </tbody>
        </table>
    </div>
    <!-- paginator -->
    <div class="col-12">
        <ul class="paginator">
            @{
                var back = index > 1 ? "" : "disabled";
                var next = index != lastPage ? "" : "disabled";
            }
            <li class="paginator__item paginator__item--prev @back">

                <a href="@routeUrl@(index - 1)" class="">
                    <i class="icon ion-ios-arrow-back"></i>
                </a>
            </li>
            @{
                if (index > 1)
                {
                    <li class="paginator__item ">
                        <a href="@routeUrl@(index - 1)">@(index - 1)</a>
                    </li>
                }
                <li class="paginator__item paginator__item--active">
                    <a>@index</a>
                </li>
                if (index != lastPage)
                {
                    <li class="paginator__item">
                        <a href="@routeUrl@(index + 1)">@(index + 1)</a>
                    </li>
                }
            }
            <li class="paginator__item paginator__item--next @next">
                <a href="@routeUrl@(index + 1)">
                    <i class="icon ion-ios-arrow-forward"></i>
                </a>
            </li>
        </ul>
    </div>
    <!-- end paginator -->
</div>

</div>
</div>
</div>

<script src="~/js/Notification.js"></script>
<script>
function ChangeIsActive(mangaId,isActive) {
  $.ajax({
          url: 'http://localhost:5098/Manga/ChangeIsActive',
          type: "PUT",
          headers: {"ACCESS_TOKEN": localStorage.getItem('ACCESS_TOKEN')},
          data: {
              mangaId: mangaId
          }, success: function () {
              ShowNotificationSuccess('Cập nhật thành công');
              if (isActive==='True'){
                  $('#isActive-'+mangaId).html(`
                  <button class="btn-status-red" type="submit" onclick="ChangeIsActive('${mangaId}','False')">
                        <i class="icon ion-ios-eye-off"></i>
                  </button>
                `);
              }else {
                  $('#isActive-'+mangaId).html(`
                  <button class="btn-status-green" type="submit" onclick="ChangeIsActive('${mangaId}','True')">
                        <i class="icon ion-ios-eye"></i>
                  </button>
                  `);    
              }
              
          }, error: function () {
              ShowNotificationError('Cập nhật thất bại');
          }
      });
}
</script>